### ISSUE TITLE
Create Navbar so it is universal across all of the pages

### ISSUE THREAD

**Issue by LucyJefford** [DabHands/museum-project#25]
**Describe the solution you'd like**
A navbar based on our designs

- [x] Research how to do it with material io
- [x] When it is viewed on a computer, have it across the top with all links visible
- [x] When it is viewed on a mobile device, have only logo/title visible & have a hamburger menu for the rest of the links

**Additional steps**
- [ ] Write tests to cover the new functionality
- [ ] Manual testing for bugs

**Comment by adyvoynova** [comment]
After researching how to use material components, I decided it would be easier and more flexible for us to create our components using Styled Components, as we have already started.

**Comment by adyvoynova** [comment]
The final design of the NavBar is not decided yet. Once it is decided, tests can be added to make sure that the app works as expected.

**Comment by adyvoynova** [comment]
The interface should be responsive, so when viewd on a laptop or a tablet, the NavBar should be styled in one way, and when viewed on a mobile device, the Navbar should be styled in another way. To be able to do this, a react library is required. It is called [react-responsive](https://www.npmjs.com/package/react-responsive).
