### ISSUE TITLE
Set up the backend

### ISSUE THREAD

**Issue by adyvoynova** [DabHands/museum-project#5]
A major part of the project will be stored as a backend - this is the image recognition part. Hence, a very basic requirement is to research what is needed for the recognition and set up some fundamentals.

**Scenarios to cover**
- [ ] Research what is needed for the backend
- [ ] Set up some basic functionalities

**Comment by LucyJefford** [comment]
Do we need to do the backend at this point in time? Recognition service is currently the only identified backend requirement

**Comment by adyvoynova** [comment]
Yes, you are right! You can close the issue and mark it as done if you want.
